"""
Type definitions for the Briefcase AI Telemetry SDK.
"""

from typing import Any, Dict, Optional, Protocol


class EventLevelProtocol(Protocol):
    """Protocol for EventLevel objects."""

    @staticmethod
    def debug() -> "EventLevelProtocol": ...

    @staticmethod
    def info() -> "EventLevelProtocol": ...

    @staticmethod
    def warning() -> "EventLevelProtocol": ...

    @staticmethod
    def error() -> "EventLevelProtocol": ...

    @staticmethod
    def critical() -> "EventLevelProtocol": ...


class EventMetadataProtocol(Protocol):
    """Protocol for EventMetadata objects."""

    def with_user_id(self, user_id: str) -> None: ...
    def with_trace_id(self, trace_id: str) -> None: ...
    def add_tag(self, key: str, value: str) -> None: ...
    def add_custom_data(self, key: str, value: Any) -> None: ...

    @property
    def user_id(self) -> Optional[str]: ...

    @property
    def trace_id(self) -> Optional[str]: ...

    @property
    def tags(self) -> Dict[str, str]: ...


class EventProtocol(Protocol):
    """Protocol for Event objects."""

    @property
    def id(self) -> str: ...

    @property
    def name(self) -> str: ...

    @property
    def level(self) -> EventLevelProtocol: ...

    @property
    def timestamp(self) -> str: ...

    @property
    def message(self) -> Optional[str]: ...

    @property
    def duration_ms(self) -> Optional[int]: ...

    @property
    def error(self) -> Optional[str]: ...


class EventBuilderProtocol(Protocol):
    """Protocol for EventBuilder objects."""

    def level(self, level: EventLevelProtocol) -> "EventBuilderProtocol": ...
    def message(self, message: str) -> "EventBuilderProtocol": ...
    def user_id(self, user_id: str) -> "EventBuilderProtocol": ...
    def tag(self, key: str, value: str) -> "EventBuilderProtocol": ...
    def custom_data(self, key: str, value: Any) -> "EventBuilderProtocol": ...
    def duration_ms(self, duration_ms: int) -> "EventBuilderProtocol": ...
    def error(self, error: str) -> "EventBuilderProtocol": ...
    def build(self) -> EventProtocol: ...


class SessionProtocol(Protocol):
    """Protocol for Session objects."""

    def with_user_id(self, user_id: str) -> "SessionProtocol": ...
    def add_metadata(self, key: str, value: Any) -> "SessionProtocol": ...

    @property
    def id(self) -> str: ...

    @property
    def user_id(self) -> Optional[str]: ...

    @property
    def started_at(self) -> str: ...


class TelemetryConfigProtocol(Protocol):
    """Protocol for TelemetryConfig objects."""

    def with_endpoint(self, endpoint: str) -> None: ...
    def with_timeout_seconds(self, timeout_seconds: int) -> None: ...
    def with_retry_attempts(self, retry_attempts: int) -> None: ...
    def with_batch_size(self, batch_size: int) -> None: ...
    def with_flush_interval_seconds(self, flush_interval_seconds: int) -> None: ...
    def with_enabled(self, enabled: bool) -> None: ...

    @property
    def api_key(self) -> str: ...

    @property
    def endpoint(self) -> str: ...

    @property
    def enabled(self) -> bool: ...


class TelemetryClientProtocol(Protocol):
    """Protocol for TelemetryClient objects."""

    def with_session(self, session: SessionProtocol) -> None: ...
    def track_event(self, event: EventProtocol) -> None: ...
    def flush(self) -> None: ...
    def start_background_flush(self) -> None: ...
    def buffer_size(self) -> int: ...
    def session(self) -> SessionProtocol: ...


# Type aliases for common data structures
Tags = Dict[str, str]
CustomData = Dict[str, Any]
Metadata = Dict[str, Any]
